### PR TITLE
Feat/casparcg route

### PR DESCRIPTION
**Pull request by jesperstarkar**
Adds the ability for CasparCG Server 2.1.11.NRK route:// producers to be controlled as sources from Sisyfos

### CODE REVIEW

**Comment by jesperstarkar** [comment]
Ignore the large commits, they come since the project is missing linting rules.

I have split linter commits out, to make the real changes simpler to review

**Comment by olzzon** [comment]
Could you revert the two lint commits, then I´ll look into linting the whole project afterward.
Beside that the code looks fine to merge.

**Comment by olzzon** [comment]
@jesperstarkar 
Could you revert the two lint commits, then I´ll look into linting the whole project afterward.
Beside that the code looks fine to merge.

**Comment by jesperstarkar** [comment]
@olzzon ready to be merged

**Pull request merged**
